export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';

// export const ADD_COURSES_REQUEST = 'ADD_COURSES_REQUEST';
export const ADD_COURSES_SUCCESS = 'ADD_COURSES_SUCCESS';
export const ADD_COURSES_FAIL = 'ADD_COURSES_FAIL';

// export const PATCH_COURSES_REQUEST = 'PATCH_COURSES_REQUEST';
export const PATCH_COURSES_SUCCESS = 'PATCH_COURSES_SUCCESS';
export const PATCH_COURSES_FAIL = 'PATCH_COURSES_FAIL';

// export const DELETE_COURSES_REQUEST = 'DELETE_COURSES_REQUEST';
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSES_SUCCESS';
export const DELETE_COURSES_FAIL = 'DELETE_COURSES_FAIL';

export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';

// export const ADD_STUDENTS_REQUEST = 'ADD_STUDENTS_REQUEST';
export const ADD_STUDENTS_SUCCESS = 'ADD_STUDENTS_SUCCESS';
export const ADD_STUDENTS_FAIL = 'ADD_STUDENTS_FAIL';

// export const PATCH_STUDENTS_REQUEST = 'PATCH_STUDENTS_REQUEST';
export const PATCH_STUDENTS_SUCCESS = 'PATCH_STUDENTS_SUCCESS';
export const PATCH_STUDENTS_FAIL = 'PATCH_STUDENTS_FAIL';

// export const DELETE_STUDENTS_REQUEST = 'DELETE_STUDENTS_REQUEST';
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS';
export const DELETE_STUDENTS_FAIL = 'DELETE_STUDENTS_FAIL';

// export const SET_ERROR = 'SET_ERROR';
// export const CLEAR_ERROR = 'CLEAR_ERROR';
