export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAIL = 'FETCH_COURSES_FAIL';

// export const ADD_COURSES_REQUEST = 'ADD_COURSES_REQUEST';
export const ADD_COURSES_SUCCESS = 'ADD_COURSES_SUCCESS';
export const ADD_COURSES_FAIL = 'ADD_COURSES_FAIL';

// export const DELETE_COURSES_REQUEST = 'DELETE_COURSES_REQUEST';
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSES_SUCCESS';
export const DELETE_COURSES_FAIL = 'DELETE_COURSES_FAIL';

// export const SET_ERROR = 'SET_ERROR';
// export const CLEAR_ERROR = 'CLEAR_ERROR';
